### ISSUE TITLE
Crashing on MPS (apple m3 32gb)

### ISSUE THREAD

**Issue by cchance27** [akatz-ai/ComfyUI-Depthflow-Nodes#12]
After it loads the depthflow model it seems something goes... VERY wrong, and crashes python.

```
loaded completely 0.0 319.7467155456543 True
Downloading model to: /Users/cc/AI/ComfyUI/models/depthanything/depth_anything_v2_vitl_fp16.safetensors
Fetching 1 files: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.79s/it]
Loading model from: /Users/cc/AI/ComfyUI/models/depthanything/depth_anything_v2_vitl_fp16.safetensors
INFO:dinov2:using MLP layer as FFN
using MLP layer as FFN
(mpsFileLoc): /AppleInternal/Library/BuildRoots/c7c74b64-74b4-11ef-aeda-9635a580fe0d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:233:0: error: 'mps.add' op requires the same element type for all operands and results
(mpsFileLoc): /AppleInternal/Library/BuildRoots/c7c74b64-74b4-11ef-aeda-9635a580fe0d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:233:0: note: see current operation: %7 = "mps.add"(%5, %arg2) : (tensor<1x5330x4096xf32>, tensor<4096xf16>) -> tensor<*xf32>
(mpsFileLoc): /AppleInternal/Library/BuildRoots/c7c74b64-74b4-11ef-aeda-9635a580fe0d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:233:0: error: 'mps.add' op requires the same element type for all operands and results
(mpsFileLoc): /AppleInternal/Library/BuildRoots/c7c74b64-74b4-11ef-aeda-9635a580fe0d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:233:0: note: see current operation: %7 = "mps.add"(%5, %arg2) : (tensor<1x5330x4096xf32>, tensor<4096xf16>) -> tensor<*xf32>
/AppleInternal/Library/BuildRoots/c7c74b64-74b4-11ef-aeda-9635a580fe0d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphExecutable.mm:988: failed assertion `original module failed verification'
[1]    661 abort      PYTORCH_ENABLE_MPS_FALLBACK=1 python main.py
/opt/homebrew/anaconda3/envs/py10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by Tremeschin** [comment]
I'm not familiar with Apple platform, but from a quick search there exists indeed a [MPS](https://pytorch.org/docs/stable/notes/mps.html) backend I didn't know of, as on my end of the code I'm only sending the models to either cuda or cpu. We could try monkey patching it with:

```python
# Add this anywhere on akatz's __init__.py or your custom scripts files
from Broken.Externals import ExternalTorchBase

@property
def device(self):
    self.load_torch()
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"

ExternalTorchBase.device = device
```

Part of me says it could be a bad torch package in anaconda<sup>unlikely</sup>, but sending to the right device yours torch package was built for could fix it. I'm mostly worried of this `fp16.safetensors` model file¹, which from what I know requires some level of driver support compared to a float32 version though

I would try switching to `depth_anything_v2_vitl_fp32.safetensors` first, and then try the fp16 with this monkey patch for using the "mps" device on torch. Let us know how all of this goes! 🙂 

¹<sup>: apparently apparently got from [Kijai](https://huggingface.co/Kijai/DepthAnythingV2-safetensors/tree/main)?</sup>

**Comment by akatz-ai** [comment]
Hi @cchance27, are you running the depthflow showcase workflow I posted? Or is this a custom workflow? And if so which node is it failing at, the depth estimator or depthflow node?

**Comment by cchance27** [comment]
No it's not that one but honestly it's just crashing as soon as it tries to load the model it seems like...

![image](https://github.com/user-attachments/assets/224c6057-3203-478f-b14b-0379dec9e928)

whats odd is swapping to fp32 seems to work... so seems like somehow the fp16 version is breaking something
i'd imagine this is due to the error "mps.add' op requires the same element type for all operands and results"

so when loading fp16 model somewhere its getting mps.add'd to a fp32 somewhere in code so fp16+fp32 = crash, fp32+fp32 = success

**Comment by akatz-ai** [comment]
using fp32 on mac seems to fix this issue, closing for now
