### ISSUE TITLE
ShaderScene.main() got an unexpected keyword argument 'freewheel'

### ISSUE THREAD

**Issue by slmonker** [akatz-ai/ComfyUI-Depthflow-Nodes#13]
just updated my torch to 2.4.1+cuda 12.4.then this come out.

**Comment by akatz-ai** [comment]
Hi @slmonker, did you install the node pack through the manager or manually via git clone? If using the manager can you please try uninstalling the custom node and reinstalling?

**Comment by mwoody450** [comment]
I'm using Comfy for the first time and am getting this same error.  More errors below.  I tried an uninstall, restart, reinstall using the manager; no change.  Inputs are a 1024x1024 image, same resolution depth map generated by MiDaS, and the input from any of the depthflow motion control nodes.

```
│DepthFlow├┤23'41.279├┤INFO   │ ▸ OpenGL Renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
!!! Exception during processing !!! ShaderScene.main() got an unexpected keyword argument 'freewheel'
Traceback (most recent call last):
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\depthflow.py", line 320, in apply_depthflow
    scene.main(
TypeError: ShaderScene.main() got an unexpected keyword argument 'freewheel'
```

**Comment by slmonker** [comment]
> Hi @slmonker, did you install the node pack through the manager or manually via git clone? If using the manager can you please try uninstalling the custom node and reinstalling?

i installed it by gitclone and in the manager install with GitURL,ok i will try to reinstall it ,thx

**Comment by slmonker** [comment]
> Hi @slmonker, did you install the node pack through the manager or manually via git clone? If using the manager can you please try uninstalling the custom node and reinstalling?

ShaderScene.main() got an unexpected keyword argument 'freewheel'

still not working

**Comment by akatz-ai** [comment]
I just updated the node pack with #14 to detect a depthflow version mismatch (the cause of the "freewheel" error) and install the latest version. Please try updating the node pack once again and then rebooting comfyui once or twice to see if the issue persists.

**Comment by slmonker** [comment]
> I just updated the node pack with #14 to detect a depthflow version mismatch (the cause of the "freewheel" error) and install the latest version. Please try updating the node pack once again and then rebooting comfyui once or twice to see if the issue persists.

roger that！

**Comment by mwoody450** [comment]
Thanks but... something definitely went very wrong there.  Admittedly, I updated a few things at once (ImpactPack, Manager, Depthflow) but it rendered Comfy unbootable.  I'm working to fix it now, just warning anyone else to not update.  I've managed to get it to boot, though DepthFlow is listed as "IMPORT FAILED"

**Comment by slmonker** [comment]
> Thanks but... something definitely went very wrong there. Admittedly, I updated a few things at once (ImpactPack, Manager, Depthflow) but it rendered Comfy unbootable. I'm working to fix it now, just warning anyone else to not update. I've managed to get it to boot, though DepthFlow is listed as "IMPORT FAILED"

me too，i just repaired my comfyui requirements 5mins ago，i had to update_comfyui_and_python_dependencies 1st then reinstall Pytorch 2.4.1+cu124........

**Comment by mwoody450** [comment]
> > Thanks but... something definitely went very wrong there. Admittedly, I updated a few things at once (ImpactPack, Manager, Depthflow) but it rendered Comfy unbootable. I'm working to fix it now, just warning anyone else to not update. I've managed to get it to boot, though DepthFlow is listed as "IMPORT FAILED"
> 
> me too，i just repaired my comfyui requirements 5mins ago，i had to update_comfyui_and_python_dependencies 1st then reinstall Pytorch 2.4.1+cu124........

Yeah I got it to boot again by removing all updated folders from custom_notes and running the comfyui + python update script.  Glad it wasn't something I just screwed up.

**Comment by slmonker** [comment]
> > > Thanks but... something definitely went very wrong there. Admittedly, I updated a few things at once (ImpactPack, Manager, Depthflow) but it rendered Comfy unbootable. I'm working to fix it now, just warning anyone else to not update. I've managed to get it to boot, though DepthFlow is listed as "IMPORT FAILED"
> > 
> > 
> > me too，i just repaired my comfyui requirements 5mins ago，i had to update_comfyui_and_python_dependencies 1st then reinstall Pytorch 2.4.1+cu124........
> 
> Yeah I got it to boot again by removing all updated folders from custom_notes and running the comfyui + python update script. Glad it wasn't something I just screwed up.

No matter how messy it is ,comfyui+python update script always fix it,wat we have to do next just simply update pytorch,cuda and xfromers……

**Comment by akatz-ai** [comment]
Yeah the unfortunate reality in comfyui is there's no good version management system in place, so everyone has different versions of custom nodes, python packages, etc. and it's impossible for developers to test against all of those combinations. I know the developers of comfy and the manager are working on a solution, but it may take some time to get it integrated. Until then we have to put up with errors like this which are frustrating for everyone involved.

**Comment by mwoody450** [comment]
I've tried everything including rolling back pytorch versions; I can't make Depthflow work, though all other node packs seem alright.  I'll try it again if a fix is found; thank you for your time.

**Comment by akatz-ai** [comment]
Just pushed another change #17 that fixes an import issue with importlib_metadata. After this change I was successfully able to get depthflow working in the windows standalone portable version of ComfyUI. Please let me know if this fixes the issue.

**Comment by akatz-ai** [comment]
My recommendation now would be to try creating a fresh ComfyUI environment and trying to install the node there through the manager. If you are able to get the node installed in a new environment it means there is an issue with your current environment that is preventing Depthflow from installing the correct pip packages.
