### ISSUE TITLE
TypeError: ShaderScene.main() got an unexpected keyword argument 'benchmark'

### ISSUE THREAD

**Issue by Maelstrom2014** [akatz-ai/ComfyUI-Depthflow-Nodes#6]
2024-10-07 16:32:58.435003 │DepthFlow├┤9'41.685├┤INFO   │ ▸ (Module 115 • CustomDepthf) Initializing scene 'CustomDepthflowScene' with backend headless
│DepthFlow├┤9'41.783├┤INFO   │ ▸ (Module 115 • CustomDepthf) OpenGL Renderer: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2
!!! Exception during processing !!! ShaderScene.main() got an unexpected keyword argument 'benchmark'
Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ai\comfyui\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\depthflow.py", line 278, in apply_depthflow
    scene.main(render=False, output=None, fps=output_fps, time=duration, speed=1.0, quality=quality, ssaa=ssaa, scale=1.0, width=width, height=height, ratio=None, benchmark=True)
TypeError: ShaderScene.main() got an unexpected keyword argument 'benchmark'

**Comment by Maelstrom2014** [comment]
dont know what it is, but I deleted "benchmark=True"
from this line (ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\depthflow.py):
        scene.main(render=False, output=None, fps=output_fps, time=duration, speed=1.0, quality=quality, ssaa=ssaa, scale=1.0, width=width, height=height, ratio=None, benchmark=True)

**Comment by akatz-ai** [comment]
Hi @Maelstrom2014, if you're still encountering this error can you please run a "pip freeze" in the same venv where you run python and see which version of depthflow is installed? It should be depthflow==0.6.0 ideally.

**Comment by akatz-ai** [comment]
Closing this as it should be fixed with the latest update #14 which attempts to detect depthflow version mis-matches and downloads the correct version.
