### ISSUE TITLE
working time please

### ISSUE THREAD

**Issue by Maelstrom2014** [akatz-ai/ComfyUI-Depthflow-Nodes#7]
Please write working time for 1024x1024 with default 30 frames settings
I stoped after 20 min of processing. Smth wrong I think.

**Comment by akatz-ai** [comment]
Hi @Maelstrom2014 , on my machine with an RTX 4090 I can complete a 1024x1024 image as a 5 second animation at 30 FPS (so total 150 frames) in 3.5 seconds. So it seems like your setup may be defaulting to CPU rendering instead of using GPU. Can you please list out your hardware specs?
