### ISSUE TITLE
Exception: eglInitialize failed (0x3001)

### ISSUE THREAD

**Issue by O-O1024** [akatz-ai/ComfyUI-Depthflow-Nodes#8]
I don't know how to solve it.
```
libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

!!! Exception during processing !!! eglInitialize failed (0x3001)
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 207, in apply_depthflow
    scene = CustomDepthflowScene(
  File "/root/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 12, in __init__
    DepthScene.__init__(self, **kwargs)
  File "<attrs generated init DepthFlow.Scene.DepthScene>", line 98, in __init__
    self.__attrs_post_init__()
  File "/root/miniconda3/lib/python3.10/site-packages/Broken/Core/BrokenUtils.py", line 80, in __attrs_post_init__
    method(self)
  File "/root/miniconda3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 119, in __post__
    self.build()
  File "/root/miniconda3/lib/python3.10/site-packages/DepthFlow/Scene.py", line 126, in build
    ShaderScene.build(self)
  File "/root/miniconda3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 139, in build
    self.init_window()
  File "/root/miniconda3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 533, in init_window
    self.window = importlib.import_module(module).Window(
  File "/root/miniconda3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 25, in __init__
    self.init_mgl_context()
  File "/root/miniconda3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 36, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/root/miniconda3/lib/python3.10/site-packages/moderngl/__init__.py", line 1986, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/root/miniconda3/lib/python3.10/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: eglInitialize failed (0x3001)
```

**Comment by akatz-ai** [comment]
Hi @O-O1024, where are you running ComfyUI in this case? Locally or in the cloud? Others have experienced issues running this nodepack on Runpod due to not having OpenGL acceleration available which will cause the same error message above.

**Comment by O-O1024** [comment]
> Hi @O-O1024, where are you running ComfyUI in this case? Locally or in the cloud? Others have experienced issues running this nodepack on Runpod due to not having OpenGL acceleration available which will cause the same error message above.
😲
I running it in the cloud with ssh tool.

**Comment by Tremeschin** [comment]
<div align="justify">

@O-O1024 It's definitely a driver installation issue (or the lack of) in the host server and/or docker image you're running

It's certainly possible to run it on the cloud, for example this [Google Colab](https://colab.research.google.com/drive/1C1mmq4GUrhBUeVoX04jAenE3Ex_IDqDB) notebook (slow, no gl accel), or [modal.com](https://github.com/BrokenSource/BrokenSource/blob/main/Docker/Cloud/Modal.py) script file I made, and also this community member that got it running on [Inferless](https://github.com/ctf05/Inferless) (apparently worked? #notsponsored)

- **Note**: I've got a semi-complete write up on what needs to happen to have OpenGL acceleration as akatz said [on my documentation](https://brokensrc.dev/get/docker/), at least for running a [docker image locally](https://github.com/BrokenSource/BrokenSource/blob/main/Docker/base.dockerfile), but it also applies for cloud providers

EGL is used for headless rendering without the use of a video server (X11/Wayland on Linux). If you want to disable it, set [`WINDOW_EGL=0`](https://github.com/BrokenSource/ShaderFlow/blob/678634a474a446b0df95fc6827752e558da556d0/ShaderFlow/Scene.py#L540), it'll probably try using GLX for context creation and might fail without one, in which case installing `xvfb` and prepending the command with `xvfb-run` might work but it'll use CPU rendering only (very slow)

If you have the option to modify or start off a custom docker image in your provider, then you're _maybe in luck_ to get GPU acceleration, otherwise speeds will be as bad as a couple seconds per frame as seen in colab. The most important thing; the host system [**must** have](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#driver-capabilities) the `graphics` capability enabled on NVIDIA Container Toolkit, which is out of user controls

The general idea is to start with the `nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04` image for [glvnd](https://github.com/NVIDIA/libglvnd) to actually find GPUs on the system, or if you're doing just CPU rendering to install some Ubuntu packages like `libegl1-mesa libegl1-mesa-dev` which should get `llvmpipe` (seen in colab) to pop up as a GL-capable devide (that's cpu rendering, slow)

There'll probably be quirks on each provider, for example, in modal one needs to ask their support team to move the workspace to their older runner which supports the `graphics` settings

I know talk is cheap, but without knowing what exact provider or hardware you're trying to run, it's hard to pin down to something specific, so I mainly linked resources and TLDR it here :)

But ultimately, you're missing any of `libEGL.so` in `/usr/lib/libEGL*` !

Let us know if any of this works! 🙂 

</div>

**Comment by Tremeschin** [comment]
I investigated this today; starting off a local docker images with `runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04` (_that one might use in runpod_) indeed fails with libEGL not found or initialization errors

After investigating what magic `nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04` does and trying out a lot of things, I discovered that to get [libglvnd](https://gitlab.freedesktop.org/glvnd/libglvnd/) running outside nvidia's image, we just need to do:

```dockerfile
# (Ubuntu 22.04)
RUN apt install -y libegl1-mesa libglvnd-dev libglvnd0
RUN mkdir -p /usr/share/glvnd/egl_vendor.d
RUN echo '{"file_format_version":"1.0.0","ICD":{"library_path":"/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0"}}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
```

All three packages were required for my RTX 3060 to pop up as a OpenGL renderer, and the ICD file is needed to list the nvidia as a EGL capable device; so, either modify/run these commands on a base image in runpod/other providers, or connect to them with `ssh` or remote vnc access and run those commands!

<sup><b>Note:</b> The provider must enable [`graphics`](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#driver-capabilities) capabilities on NCT on the host for OpenGL to work, hope they do or ask their support!</sup>

**Comment by Tremeschin** [comment]
### ⭐️ Big news, what I said on my previous comment seems to work for runpod!

Community member screenshot:

![image](https://github.com/user-attachments/assets/c727bdf9-d047-4edc-aec6-5cb3cad94932)

So yea, installing the three packages and the icd file did the trick! We now have a cloud provider with OpenGL acceleration working, without needing to ask their support team, with only minor intervention needed 🙂

**Comment by akatz-ai** [comment]
Closing this as it appears to be fixed based on the docker code provided in the mentioned issue above.

**Comment by killy001** [comment]
`2024-12-25T07:16:12.116290 - Prompt executed in 2.25 seconds
2024-12-25T07:17:24.201205 - got prompt
2024-12-25T07:17:24.254405 - │DepthFlow├┤1'22.937├┤INFO   │ ▸ (Module  2 • CustomDepthf) Initializing scene 'CustomDepthflowScene' with backend headless
2024-12-25T07:17:24.264139 - !!! Exception during processing !!! eglGetPlatformDisplayEXT failed (0x3000)
2024-12-25T07:17:24.264436 - Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 293, in apply_depthflow
    scene = CustomDepthflowScene(
  File "/app/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 59, in __init__
    DepthScene.__init__(self, **kwargs)
  File "<attrs generated init DepthFlow.Scene.DepthScene>", line 101, in __init__
    self.__attrs_post_init__()
  File "/usr/local/python3/lib/python3.10/site-packages/Broken/Core/__init__.py", line 504, in __attrs_post_init__
    method(self)
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 120, in __post__
    self._build()
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 138, in _build
    self.init_window()
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 495, in init_window
    self.window = importlib.import_module(module).Window(
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 25, in __init__
    self.init_mgl_context()
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 36, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl/__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/usr/local/python3/lib/python3.10/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: eglGetPlatformDisplayEXT failed (0x3000)`

**Comment by killy001** [comment]
```
2024-12-25T07:16:12.116290 - Prompt executed in 2.25 seconds
2024-12-25T07:17:24.201205 - got prompt
2024-12-25T07:17:24.254405 - │DepthFlow├┤1'22.937├┤INFO   │ ▸ (Module  2 • CustomDepthf) Initializing scene 'CustomDepthflowScene' with backend headless
2024-12-25T07:17:24.264139 - !!! Exception during processing !!! eglGetPlatformDisplayEXT failed (0x3000)
2024-12-25T07:17:24.264436 - Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 293, in apply_depthflow
    scene = CustomDepthflowScene(
  File "/app/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 59, in __init__
    DepthScene.__init__(self, **kwargs)
  File "<attrs generated init DepthFlow.Scene.DepthScene>", line 101, in __init__
    self.__attrs_post_init__()
  File "/usr/local/python3/lib/python3.10/site-packages/Broken/Core/__init__.py", line 504, in __attrs_post_init__
    method(self)
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 120, in __post__
    self._build()
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 138, in _build
    self.init_window()
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 495, in init_window
    self.window = importlib.import_module(module).Window(
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 25, in __init__
    self.init_mgl_context()
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 36, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl/__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/usr/local/python3/lib/python3.10/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: eglGetPlatformDisplayEXT failed (0x3000)
```

**Comment by ThomasRoyer24** [comment]
> I investigated this today; starting off a local docker images with `runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04` (_that one might use in runpod_) indeed fails with libEGL not found or initialization errors
> 
> After investigating what magic `nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04` does and trying out a lot of things, I discovered that to get [libglvnd](https://gitlab.freedesktop.org/glvnd/libglvnd/) running outside nvidia's image, we just need to do:
> 
> # (Ubuntu 22.04)
> RUN apt update && apt install -y libegl1-mesa libglvnd-dev libglvnd0
> RUN mkdir -p /usr/share/glvnd/egl_vendor.d
> RUN echo '{"file_format_version":"1.0.0","ICD":{"library_path":"/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0"}}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
> 
> # Could also be important
> ENV NVIDIA_DRIVER_CAPABILITIES="all"
> ENV NVIDIA_VISIBLE_DEVICES="all"
> All three packages were required for my RTX 3060 to pop up as a OpenGL renderer, and the ICD file is needed to list the nvidia as a EGL capable device; you can modify or run these commands on a base image in runpod or similar providers, or connect via SSH or remote VNC access to execute the commands directly!
> 
> Note: The provider must enable [`graphics`](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#driver-capabilities) capabilities on NCT on the host for OpenGL to work, hope they do or ask their support!
> 
> let us know if this works for whatever provider you might be running!

Hello Tremeschin. First of all, thank you for your work on the depthflow project and for the time you spend solving problems. 

I encountered the problem eglInitialize failed (0x3001) on my docker machine. I followed your instructions to get openGL working.
I now have 2 new problems. when I run my worflow on Comfyui, the Depthflow node works fine but bugs at the very end, as shown in the image below. 

![Image](https://github.com/user-attachments/assets/569d7268-67e1-4b45-9e3d-c94574876ada)

![Image](https://github.com/user-attachments/assets/1e584e1c-0f31-4a12-a954-893d6bf049a3)

The workflow blocks and comfyui shuts down.

So I restarted Comfyui and this time if the worflow this block to load audio with [ComfyUI-VideoHelperSuite](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite). 
As shown in the image below, there's a bug loading ffpmeg. (PID 87)

![Image](https://github.com/user-attachments/assets/8a0e22c2-570a-494e-ac6a-d19b8ade16da)

I followed the instructions of [issue52](https://github.com/BrokenSource/DepthFlow/issues/52), but that doesn't solve the performance problem or the ffpmeg problem I mentioned before. 

I'll put some info on my docker if that helps.

docker compose :
version: '3.8'

services:
`  comfyui:
    build:
      context: .
      dockerfile: comfy-dockerfile
    volumes:
      - ./database:/database
      - /usr/lib/wsl:/usr/lib/wsl
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
              
    stdin_open: true
    tty: true
    networks:
      - app_network`

Docker file:
`
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1

# Installer les dépendances nécessaires pour ajouter Python 3.10
RUN apt-get update && \
    apt-get install -y git wget software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.10 python3.10-dev python3.10-distutils && \
    apt-get clean && \
    apt-get install -y curl && \
    apt-get install -y libgl1

#Telecharger Comfyui
RUN --mount=type=cache,target=/root/.cache/pip \
  git clone https://github.com/comfyanonymous/ComfyUI.git ${ROOT} && \
  cd ${ROOT} && \
  git checkout master && \
  #git reset --hard put-commit-version && \
  python3.10 -m pip install -r requirements.txt

# Fixme: Why BtbN FFmpeg binaries "are faster" than 'apt install ffmpeg' one?
ARG FFMPEG_FLAVOR="ffmpeg-master-latest-linux64-gpl"
ARG FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FFMPEG_FLAVOR}.tar.xz"
RUN curl -L ${FFMPEG_URL} | tar -xJ --strip-components=2 --exclude="doc" --exclude="man" -C /usr/local/bin

# libEGL / nvidia
RUN apt install -y libegl1-mesa libglvnd-dev libglvnd0
RUN mkdir -p /usr/share/glvnd/egl_vendor.d
RUN echo '{"file_format_version":"1.0.0","ICD":{"library_path":"/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0"}}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
ENV NVIDIA_DRIVER_CAPABILITIES="all"
ENV NVIDIA_VISIBLE_DEVICES="all"


ENV NVIDIA_VISIBLE_DEVICES=all PYTHONPATH="${PYTHONPATH}:${PWD}" CLI_ARGS=""
EXPOSE 7860

CMD ["/bin/bash"]`

I don't put all my docker file so as not to overload the text.

If you need anything, don't hesitate to ask me.

**Comment by Tremeschin** [comment]
@ThomasRoyer24 Could you try saving the following to a `issue8.dockerfile` or something and see if it works from my "official" docker images in github container registry?

```dockerfile
FROM ghcr.io/brokensource/shaderflow:0.9.0.dev0-cpu
CMD ["shaderflow", "basic", "main", "-o", "/tmp/video.mp4"]
```

To run it: `docker build -t issue8 -f issue8.dockerfile . && docker run --gpus all --rm issue8`

We're only checking for the GPU to be found as a EGL capable device as below:

![Image](https://github.com/user-attachments/assets/640772f2-5c89-4f04-be36-a216510c1665)

**Comment by Tremeschin** [comment]
<div text-align="justify">
<details><summary> As for the workflow halting and FFmpeg, <sup>(Click to expand)</sup></summary>

<br>

That ffmpeg process seems to be called from the VideoHelperSuite nodes (to read an audio file?), as my ffmpeg commands would start with `--hide_banner`, `-loglevel error`, etc.

The code printing that `Stats: (Took Xs)` part means the video was successfully rendered to completion from my end. My first guess is that either the final encoding command from video helper nodes is expecting a couple more frames (differences in how one calculates time?), or that it was never called / crashed on differing input types than expected?

I'm not into Comfy but does the object type of "images" that akatz's nodes outputs is what the video helper expects it to be?

I think he's doing numpy arrays, while video combine could expect pngs/jpegs? Try checking for those, run some workflow that you know works in video helper see if it has its own FFmpeg encoding process that's not appearing here

Hope this helps! 🙂

</details>

**Comment by ThomasRoyer24** [comment]
> [@ThomasRoyer24](https://github.com/ThomasRoyer24) Could you try saving the following to a `issue8.dockerfile` or something and see if it works from my "official" docker images in github container registry?
> 
> FROM ghcr.io/brokensource/shaderflow:0.9.0.dev0-cpu
> CMD ["shaderflow", "basic", "main", "-o", "/tmp/video.mp4"]
> To run it: `docker build -t issue8 -f issue8.dockerfile . && docker run --gpus all --rm issue8`
> 
> We're only checking for the GPU to be found as a EGL capable device as below:
> 
> ![Image](https://github.com/user-attachments/assets/640772f2-5c89-4f04-be36-a216510c1665)

![Image](https://github.com/user-attachments/assets/55fb164e-1738-414a-8f49-241bdfa175b5)

**Comment by ThomasRoyer24** [comment]
it seems that my GPU is detected as an EGL-compatible device? It shouldn't have the performance problem then?

**Comment by Tremeschin** [comment]
Can you run `docker run --rm --gpus all ghcr.io/brokensource/glinfo:0.9.0.dev0-cpu` for diagnosis and send a link with the full output in a secret https://gist.github.com/ (or other site of your preference)?
